name: scattering-problem-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.6
  - numpy=1.26.4
  - scipy=1.13.1
  - matplotlib=3.8.4
  - pytorch==2.3.0
  - pyDOE==0.3.8
  - pandas==2.2.3
  - gmsh==4.13.1
  - meshio==5.3.5